# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 997b930058900b9095da2269f00b5e47e0a232a851a1fa71d7097928195007be58c6ed85d734b59eeae49a8a7e07bb176bb1503510b7f8f3b32b48e2a8baf161

test:
  secret_key_base: 2b2add8ad12c9863169c8b70e262fb7516bf79f19ef714f12d52d2dfac25bfb0966369fae3c2af54f1909d6fd947092f2fd85721bf9ca3e69874fd52d396453b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
